### ISSUE TITLE
ship the license with the source on pypi

### ISSUE THREAD

**Issue by hmaarrfk** [vpelletier/python-libaio#10]
I think it needs the following in  `setup.cfg`

```
[metadata]
license_file = COPYING.LESSER
```

**Comment by vpelletier** [comment]
Mmh, COPYING.LESSER seems to be included by default:
```
$ python setup.py sdist check
[...]
copying COPYING.LESSER -> libaio-0.6+2.g693a8d6
[...]
$ tar tf dist/libaio-0.6+2.g693a8d6.tar.gz 
libaio-0.6+2.g693a8d6/
libaio-0.6+2.g693a8d6/COPYING.LESSER
[...|
```

But you anyway have a point, COPYING needs to be included as well.

**Comment by vpelletier** [comment]
MANIFEST.in seems to do the trick:

```
$ python setup.py sdist check
[...]
copying COPYING -> libaio-0.6+2.g693a8d6.dirty
copying COPYING.LESSER -> libaio-0.6+2.g693a8d6.dirty
[...]
$ tar tf dist/libaio-0.6+2.g693a8d6.dirty.tar.gz 
libaio-0.6+2.g693a8d6.dirty/
libaio-0.6+2.g693a8d6.dirty/COPYING.LESSER
[...]
libaio-0.6+2.g693a8d6.dirty/COPYING
[...]
$ git diff
diff --git a/MANIFEST.in b/MANIFEST.in
index 5ae2f59..2f98fde 100644
--- a/MANIFEST.in
+++ b/MANIFEST.in
@@ -1,2 +1,4 @@
 include versioneer.py
 include libaio/_version.py
+include COPYING
+include COPYING.LESSER
```

**Comment by vpelletier** [comment]
May be fixed by d0909070273692f3151bf06dd9924fa8a6e0bf3a . But I'm not too familiar with even basic setup.py-based packaging (ex: I'm sad that `setup.py upload` complains that it's deprecated), so I may be wrong, so feel free to reopen.

**Comment by hmaarrfk** [comment]
Yes you do have quite odd tricks to get things to work!!!

I haven't seen 2to3 being used in a setup file before. It does break development mode installs for python3. makes me sad.

**Comment by hmaarrfk** [comment]
Travis somewhat automated the process of uploading
https://github.com/hmaarrfk/redpil/blob/master/.travis.yml

if you subscribe to the "tag the versions you want to publish" philosophy, that should almost do it.
